name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ci-agent
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: actions/runner-images
          
      - name: Build image
        run: ./images.CI/linux-and-win/build-image.ps1 `
              -TemplatePath linux `
              -ResourcesNamePrefix 1
