name: MMS image generation
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: An OS image to build
        options:
          - ubuntu2004
          - ubuntu2204
          - windows2019
          - windows2022
        required: true
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: linux-agents
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: mikhailkoliada/runner-images
          ref: 'packer_ub_disable_color'
          
      - name: Set image varibles
        run: |
          $ImageType = "${{ github.event.inputs.choice }}"

          if ($ImageType.StartsWith("ubuntu")) { $TemplateDirectoryName = "linux" } else { $TemplateDirectoryName = "win" }
          
          $TemplateDirectoryPath = Join-Path "images" $TemplateDirectoryName | Resolve-Path
          $TemplatePath = Join-Path $TemplateDirectoryPath "$ImageType.pkr.hcl"
          
          if ( -not (Test-Path $TemplatePath) ) {
            $TemplatePath = Join-Path $TemplateDirectoryPath "$ImageType.json"
          } 
          
          echo "::set-env name=TemplatePath::$TemplatePath"
          echo "::set-env name=TemplateDirectoryPath::$TemplateDirectoryPath"
        env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
      - name: Build image
        run: |
            ./images.CI/linux-and-win/build-image.ps1 `
              -TemplatePath $env:TemplatePath `
              -ClientId ${{ secrets.CLIENT_ID }} `
              -ClientSecret ${{ secrets.CLIENT_SECRET }} `
              -Location ${{ secrets.AZURE_LOCATION }} `
              -ResourcesNamePrefix ${{github.run_number}} `
              -ResourceGroup ${{ secrets.AZURE_RESOURCE_GROUP }} `
              -StorageAccount ${{ secrets.AZURE_STORAGE_ACCOUNT }} `
              -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION }} `
              -TenantId ${{ secrets.AZURE_TENANT }}
              
