name: MMS image generation
on:
  workflow_dispatch:
    inputs:
      PLATFORM:
        description: An OS image to build
        required: false
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: linux-agents
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: actions/runner-images
          
      - name: Set image varibles
        run: |
          $ImageType="${{ github.event.inputs.PLATFORM }}"

          if ($ImageType.StartsWith("ubuntu")) { $TemplateDirectoryName = "linux" } else { $TemplateDirectoryName = "win" }
          
          $TemplateDirectoryPath="images/$TemplateDirectoryName"
          $TemplatePath="$TemplateDirectoryPath/$ImageType.pkr.hcl"
          
          if ( -not $TemplatePath) { $TemplatePath=$TemplateDirectoryPath/$ImageType.json }
          
          echo "::set-env name=TemplatePath::$TemplatePath"
          echo "::set-env name=TemplateDirectoryPath::$TemplateDirectoryPath"
        env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
      - name: Build image
        run: |
            ./images.CI/linux-and-win/build-image.ps1 `
              -TemplatePath $env:TemplatePath `
              -ClientId ${{ secrets.CLIENT_ID }} `
              -ClientSecret ${{ secrets.CLIENT_SECRET }} `
              -ResourcesNamePrefix 1
