name: Ubuntu-22.04
on:
  workflow_dispatch:
jobs:
  generate-image:
    runs-on: ci-agent
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: actions/runner-images
          
      - name: Generate Ubuntu 20.04
        uses:  ./.github/workflows/ubuntu-win-generation.yml
