name: MMS image generation
on:
  workflow_dispatch:
    inputs:
      PLATFORM:
        description: An OS to build
        required: false
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ci-agent
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: actions/runner-images
          
      - name: Set image varibles
        run: |
          ImageType="${{ github.event.inputs.PLATFORM }}"

          if [[ $ImageType == "ubuntu"* ]]; then
              TemplateDirectoryName=linux
          else
              TemplateDirectoryName=win
          fi
          
          TemplateDirectoryPath="images/$TemplateDirectoryName"
          TemplatePath="$TemplateDirectoryPath/$ImageType.pkr.hcl"
          
          [[ ! -e $TemplatePath ]] && TemplatePath=$TemplateDirectoryPath/$ImageType.json
          
          echo "::set-env name=TemplatePath::$TemplatePath"
          echo "::set-env name=TemplateDirectoryPath::$TemplateDirectoryPath"
        env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        shell: bash
            
         
      - name: testing
        run: | 
          ls $TemplateDirectoryPath
          ls $TemplatePath
          
      - name: Build image
        run: ./images.CI/linux-and-win/build-image.ps1 `
              -TemplatePath $TemplatePath `
              -ClientId ${{ secrets.CLIENT_ID }} `
              -ResourcesNamePrefix 1
        shell: pwsh
