name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ci-agents
    steps:
      - name: Run a multi-line script
        run: |
          packer -v
