name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ci-agent
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: actions/virtual-environments
          
      - name: Build image
        run: ls /home/runner/work/
