on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]
  
jobs:
  Ubuntu2004:
    uses: ./.github/workflows/ubuntu-win-generation.yml
    with:
      image_name: 'ubuntu2004'
    secrets: inherit
