name: MMS image generation
on:
  workflow_call:
    inputs:
      image_name:
        type: string
        description: An OS image to build
        required: true
defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: linux-agents
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'actions/runner-images'
    
      - name: Set image varibles
        run: |
          $ImageType = "${{ inputs.image_name }}"

          if ($ImageType.StartsWith("ubuntu")) { $TemplateDirectoryName = "linux" } else { $TemplateDirectoryName = "win" }
          
          $TemplateDirectoryPath = Join-Path "images" $TemplateDirectoryName | Resolve-Path
          $TemplatePath = Join-Path $TemplateDirectoryPath "$ImageType.pkr.hcl"
          
          if ( -not (Test-Path $TemplatePath) ) {
            $TemplatePath = Join-Path $TemplateDirectoryPath "$ImageType.json"
          } 
          
          echo "::set-env name=TemplatePath::$TemplatePath"
          echo "::set-env name=TemplateDirectoryPath::$TemplateDirectoryPath"
        env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
      - name: Build image
        run: |
            ./images.CI/linux-and-win/build-image.ps1 `
              -TemplatePath $env:TemplatePath `
              -ClientId ${{ secrets.CLIENT_ID }} `
              -ClientSecret ${{ secrets.CLIENT_SECRET }} `
              -Location ${{ secrets.AZURE_LOCATION }} `
              -ResourcesNamePrefix "Asad1256-" `
              -ResourceGroup ${{ secrets.AZURE_RESOURCE_GROUP }} `
              -StorageAccount ${{ secrets.AZURE_STORAGE_ACCOUNT }} `
              -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION }} `
              -TenantId ${{ secrets.AZURE_TENANT }}
              
